apiVersion: apps/v1
kind: Deployment

metadata:
  name: notes-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: notes

  template:
    metadata:
      labels:
        app: notes

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80

        volumeMounts:
        - name: notes-storage
          mountPath: /usr/share/nginx/html

      volumes:
      - name: notes-storage
        persistentVolumeClaim:
          claimName: notes-pvc
